<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'dmrch\\banner\\Plugin' => 'plugins\\dmrch\\banner\\Plugin.php',
  'october\\drivers\\Plugin' => 'plugins\\october\\drivers\\Plugin.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'dmrch\\banner\\Controllers\\banner' => 'plugins\\dmrch\\banner\\controllers\\banner.php',
  'Dmrch\\Banner\\Models\\Banner' => 'plugins\\dmrch\\banner\\models\\Banner.php',
  'cms\\Controllers\\index' => 'modules\\cms\\controllers\\index.php',
  'Dmrch\\Banner\\Components\\Banner' => 'plugins\\dmrch\\banner\\components\\Banner.php',
  'backend\\Controllers\\media' => 'modules\\backend\\controllers\\media.php',
  'dmrch\\catalog\\Plugin' => 'plugins\\dmrch\\catalog\\Plugin.php',
  'dmrch\\contact\\Plugin' => 'plugins\\dmrch\\contact\\Plugin.php',
  'Dmrch\\Contact\\Models\\MailConfig' => 'plugins\\dmrch\\contact\\models\\MailConfig.php',
  'cms\\Controllers\\themes' => 'modules\\cms\\controllers\\themes.php',
  'system\\Controllers\\updates' => 'modules\\system\\controllers\\updates.php',
);